# -*- coding: utf-8 -*-
"""DSP[SL].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PU5m68KRmvUUz8Fzu78zH6bw2bqW2yCg
"""

# ==============================================================
# 🎬 Smart Movie Recommendation System (Precomputed Version)
# Author: Revanth
# ==============================================================

import streamlit as st
import pandas as pd
import pickle
import difflib
import requests

# --------------------------------------------------------------
# PAGE CONFIG
# --------------------------------------------------------------
st.set_page_config(page_title="Smart Movie Recommendation System", page_icon="🎬", layout="centered")

# --------------------------------------------------------------
# LOAD PRECOMPUTED DATA
# --------------------------------------------------------------
@st.cache_resource
def load_precomputed_data():
    df = pickle.load(open("movies.pkl", "rb"))
    similarity = pickle.load(open("similarity.pkl", "rb"))
    return df, similarity

df, similarity = load_precomputed_data()

# --------------------------------------------------------------
# OPTIONAL POSTER FETCH FUNCTION
# --------------------------------------------------------------
def get_movie_poster(title):
    api_key = "YOUR_TMDB_API_KEY"  # Optional
    url = f"https://api.themoviedb.org/3/search/movie?api_key={api_key}&query={title}"
    try:
        response = requests.get(url, timeout=2).json()
        if response.get("results"):
            poster_path = response["results"][0].get("poster_path")
            if poster_path:
                return f"https://image.tmdb.org/t/p/w500{poster_path}"
        return "https://via.placeholder.com/150x220.png?text=No+Poster"
    except:
        return "https://via.placeholder.com/150x220.png?text=Error"

# --------------------------------------------------------------
# RECOMMEND FUNCTION
# --------------------------------------------------------------
def recommend_movies(movie_name):
    list_of_titles = df['Series_Title'].tolist()
    matches = difflib.get_close_matches(movie_name, list_of_titles, n=1)
    if not matches:
        return None, []
    movie = matches[0]
    idx = df[df.Series_Title == movie].index[0]
    scores = list(enumerate(similarity[idx]))
    sorted_scores = sorted(scores, key=lambda x: x[1], reverse=True)
    recommendations = []
    for i, movie_score in enumerate(sorted_scores[1:11]):
        index = movie_score[0]
        row = df.iloc[index]
        recommendations.append({
            "title": row.Series_Title,
            "genre": row.Genre,
            "rating": row.IMDB_Rating,
            "director": row.Director,
            "poster": get_movie_poster(row.Series_Title)
        })
    return movie, recommendations

# --------------------------------------------------------------
# STREAMLIT UI
# --------------------------------------------------------------
st.title("🎥 Smart Movie Recommendation System")
st.caption("Developed by Revanth — Using IMDb Top 1000 Dataset")
st.markdown("Find movies similar to your favorites based on genre, storyline, and cast!")

movie_name = st.text_input("🔍 Enter a movie name:")

if st.button("Recommend"):
    if movie_name.strip() == "":
        st.warning("⚠️ Please enter a movie name first.")
    else:
        with st.spinner("Finding similar movies... 🍿"):
            movie, results = recommend_movies(movie_name)

        if not results:
            st.error("❌ No similar movies found. Try another name.")
        else:
            st.success(f"🎬 Top 10 Recommendations similar to **{movie}**")
            for i, rec in enumerate(results, 1):
                col1, col2 = st.columns([1, 3])
                with col1:
                    st.image(rec["poster"], width=150)
                with col2:
                    st.subheader(f"{i}. {rec['title']}")
                    st.write(f"🎭 **Genre:** {rec['genre']}")
                    st.write(f"🎬 **Director:** {rec['director']}")
                    st.write(f"⭐ **IMDb Rating:** {rec['rating']}")
                st.markdown("---")