# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ag_jQvpAYXghXV2VhVHFIsPvhNsKQUTJ
"""

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pickle

# Load dataset
df = pd.read_csv("/content/imdb_top_1000.csv")
df = df.fillna('')

# Combine features
features = ['Genre', 'Overview', 'Director', 'Star1', 'Star2', 'Star3', 'Star4']
df['Combined_Features'] = df.apply(lambda x: ' '.join(str(x[f]) for f in features), axis=1)

# Build similarity matrix (only once)
vectorizer = CountVectorizer(stop_words='english', max_features=5000)
feature_vectors = vectorizer.fit_transform(df['Combined_Features'])
similarity = cosine_similarity(feature_vectors)

# Save both dataframe and similarity matrix
with open("movies.pkl", "wb") as f:
    pickle.dump(df, f)

with open("similarity.pkl", "wb") as f:
    pickle.dump(similarity, f)

print("✅ Preprocessing complete! Files saved: movies.pkl & similarity.pkl")